# Data Cleaning  

In this part, we would like to clean the datasets to get the useful data, and plot them to show useful information. 

## Gun Violence Data  

Our entry point is Gun Violence Data, we want to show gun violence rate in the United States. Since this dataset only consists of records from 2014 to 2018, our analysis is focused on 2014 to 2018. We only have the first quarter violence data for 2018, so the number of casualties in 2018 is smaller than other years.  
For each state, we calculated the sum of "n_killed" and "n_injured" of every incident, and divide it by the population of that year.    
We filter the data by year and state. For example, In the plot of each state in each year, we used the columns "Longitude" and "Latitude" to get the specific location of every incident. Each incident is plotted as a red dot on map.   
We also check correctness of the longitude and latitude. As the longitude range of US is (-161,-68.1). We filtered the incorrect records which are out of the range.    
Besides as we have different gun shooting types, such as "Mass Shooting", "Officer Involved", "Child/Teen Involved", "Home Invasion". These variables could represent the safety situation in each state.

## Gun Background Check Data  

We only used columns "states","date","totals", and there are no missing values in these variables. 

## Population Data

We cleaned the population data to transform it into the population by state and by year. The cleaned dataset is in the folder of "dataset", named "clean_population_by_state".  

## GDP Data  

The GDP dataset contains the GDP of each state from 1999 to 2018. And the unit of it is Millions of current dollars. 